### ISSUE TITLE
Expmple ?

### ISSUE THREAD

**Issue by frank-pian** [KKoovalsky/LlvmCrossCompileArmCortexM#1]
Nice work !
Can you provide a complex example ?
I've actually been working on the "LLVM-embedded-toolchain-for-Arm" project for a while. Their examples are simple and not very helpful.

**Comment by KKoovalsky** [comment]
Thanks! 
I intended to, but currently I am busy with other stuff. The guide [How to incorporate the libraries?](https://github.com/KKoovalsky/LlvmCrossCompileArmCortexM#how-to-incorporate-the-libraries) explains what to do to use the cross-compiled libraries. Is that you are looking for?

**Comment by frank-pian** [comment]
I have solved my problem. Thanks.
